<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\URL;
use Carbon\Carbon;

$GLOBALS['precokm'] = 0.11;
Layout::includeLayout('indexheader'); 
$allflights = Data::get('allflight');
?>
<style>
table, th, td {
	border-collapse: collapse;
	color: black;
	text-align: center;
	border-bottom: 1px solid teal;
	border-top: none;
	border-left: none;
	border-right: none;
	background-color:  rgba(224, 224, 224, 0.4) ;
}

form{
	color: teal;
	font-weight: bold;
	justify-content: space-around;
	border: teal;

}
</style>
<body id="head">
	<div class="container">
		<?php
		$precototal = 0;
		if(sizeof($allflights) > 0 ) {
			echo "<h2 style='color: teal; font-weight: bold; font-size: xx-large'>Comprar Bilhete</h2>";
			echo "<table class='container'  style='width: 100%'>";
			echo "<tr>";
			echo "<th style='color: teal; font-weight: bold; font-size: medium;'>Cidade</th>";
			echo "<th style='color:teal; font-weight: bold; font-size: medium;'>Nome do Aeroporto</th>";
			echo "<th style='color: teal; font-weight: bold; font-size: medium;'>Cidade</th>";
			echo "<th style='color:teal; font-weight: bold; font-size: medium;'>Nome do Aeroporto</th>";
			echo "<th style='color:teal; font-weight: bold; font-size: medium;'>Número Voo</th>";
			echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Distancia</th>";
			echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Companhia Aérea</th>";
			echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Data Partida</th>";
			echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Data Chegada</th>";
			echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Preço</th>";
			echo "</tr>";

		}
		foreach($allflights as $allflight){
			
			$flight = $allflight["flight"];
			$datepartida = new Carbon($flight->departure->horariopartida);
			$datechegada = new Carbon($flight->arrival->horariochegada);
			echo "<tr>";
			echo '<td>'.$flight->departure->airport->cidade.'</td>';
			echo '<td>'.$flight->departure->airport->nome.'</td>';
			echo '<td>'.$flight->arrival->airport->cidade.'</td>';
			echo '<td>'.$flight->arrival->airport->nome.'</td>';
			echo '<td>'.$flight->nvoo.'</td>';
			echo '<td>'.$flight->distancia.'</td>';
			echo '<td>'.$flight->comaerea.'</td>';
			echo '<td>'.$datepartida->toCookieString().'</td>';
			echo '<td>'.$datechegada->toCookieString().'</td>';
			global $precokm;
			$preco = $flight->distancia*$precokm;
			$precototal = $precototal + $preco;
			echo '<td>'.$preco.'€</td>';
			echo "</tr>";
		}
		?>
	</table>
</div>
<br>
<div class="container" style="background-color:  rgba(224, 224, 224, 0.4) ; width: 75%; padding: 20px; border-bottom: 5px;">
	<form method="Post" action="<?php Url::toRoute('ticket/confirmcomprar')?> ">
		<?php
		$_SESSION["allflights"] = $allflights;
		foreach($allflights as $allflight){
			$lugar = $allflight["lugar"];
			$horaembarque = $allflight["horaembarque"];
			$portaembarque = $allflight["portaembarque"];

			echo 'Hora de Embarque <input type="text" name="horarioembarque" value="'.$horaembarque.'" readonly>';
			echo 'Lugar <input type="text" name="lugar" value="'.$lugar.'" readonly>';
			echo 'Porta de Embarque <input type="text" name="portaembarque" value="'.$portaembarque.'" readonly><br>';
		}
		echo 'Preço total <input type="text" name="valor" value="'.$precototal.' €"readonly>';
		?>
		<br>
		<br>
		<br>
		<input type="submit" value="Comprar Bilhete">
	</form>
</div>
</body>

<?php Layout::includeLayout('footer') ?>