<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Url;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Redirect;

Layout::includeLayout('indexheader'); 
$peoples = Data::get('peoples');

?>
<style>
table, th, td {
	border-collapse: collapse;
	color: black;
	text-align: center;
	border-bottom: 1px solid teal;
	border-top: none;
	border-left: none;
	border-right: none;
	background-color:  rgba(224, 224, 224, 0.4) ;
}
form{
	color: teal;
	font-weight: bold;
	justify-content: space-around;
	border: teal;

}
</style>
<body id="head">
	<div class="container ">
		<h2 style='color: teal; font-weight: bold; font-size: xx-large'>Pessoal</h2> 
		<table class="container" style="border: #00b0e8; height: 30px; width: 100%;">
			<?php 
			echo "<tr>";
			echo "<th style='color: teal; font-weight: bold; font-size: large;'>Nome</th>";
			echo "<th style='color:teal; font-weight: bold; font-size: large;'>Username</th>";
			echo "<th style='color:teal; font-weight: bold; font-size: large;'>Tipo</th>";
			echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: large;'>Eliminar <br> Entrada</th>";
			echo "</tr>";

			foreach ($peoples as $people) {
				echo "<tr>";
				echo '<td>'.$people->nome .'</td>';
				echo '<td>'.$people->username.'</td>';
				if($people->tipo == "O"){
					echo '<td>Operador de Checkin</td>';
				}else{
					echo '<td>Gestor de Voo</td>';
				}
				echo '<td><a class="btn" href="'.Url::ToRoute("pessoa/destroy", $people->id).'">X</a></td>';
				echo "</tr>";
			}
			?>
		</table>
		<br>
		<br>
		<br>
		<br>
		<div class="container" style="background-color:  rgba(224, 224, 224, 0.4) ; width: 75%; padding: 20px; border-bottom: 5px;">
			<form method="post" action="<?php Url::toRoute('pessoa/store')?>">
				Nome: <input type="text" name="nome" required>
				<label for="m">Masculino</label>
				<input type="radio" id="m" name="sexo" value="M" required>
				<label for="f">Feminino</label>
				<input type="radio" id="f" name="sexo" value="F" required>
				Data de Nascimento: <input type="date" name="dtaNascimento" required> <br><br>
				NIF: <input type="text" name="nif" required>
				Morada: <input type="text" name="morada" required>
				Contacto: <input type="text" name="contacto" required><br><br>
				Username: <input type="text" name="username" required>
				Palavra-Passe: <input type="password" name="palavrapasse" required>
				<select name = "tipo">
					<option value="O">Operador de Checkin</option>
					<option value="G">Gestor de Voos</option>
				</select><br><br>
				<input type="submit">
			</form>
		</div>
	</div>
</body>
<?php Layout::includeLayout('footer') ?>