<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Url;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Redirect;

Layout::includeLayout('indexheader'); 
$allflights = Data::get('allflights');


?>
<style>
table, th, td {
	border-collapse: collapse;
	color: black;
	text-align: center;
	border-bottom: 1px solid teal;
	border-top: none;
	border-left: none;
	border-right: none;
	background-color:  rgba(224, 224, 224, 0.4) ;

}
</style>
<body id="head">
	<div class="container ">
		<h2 style='color: teal; font-weight: bold; font-size: xx-large;'>Checkin</h2> <table class="container" style='width: 85%;'>
			<br>
			<br>
			<?php

			echo "<tr>";
			echo "<th style='color: teal; font-weight: bold; font-size: large;'>Número de Voo</th>";
			echo "<th style='color:teal; font-weight: bold; font-size: large;'>Partida</th>";
			echo "<th style='color:teal; font-weight: bold; font-size: large;'>Chegada</th>";
			echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: large;'>Ver <br> Passageiros</th>";
			echo "</tr>";


			foreach ($allflights as $flight) {
				echo "<tr>";
				echo '<td>'.$flight->nvoo.'</td>';
				echo '<td>'.$flight->departure->airport->cidade.' </td>';
				echo '<td>'.$flight->arrival->airport->cidade.' </td>';
				echo '<td><a class="btn" href="'.Url::ToRoute("ticket/checkinpassengers", $flight->id).'">Ver passageiros</a></td>';
				echo "</tr>";
			}
			?>
		</table>
		<br>

	</div>
</body>
<?php Layout::includeLayout('footer') ?>