<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Url;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Redirect;

Layout::includeLayout('indexheader'); 
$flights = Data::get('flights');
$airports = Data::get('airports');
$airplanes = Data::get('airplanes');

?>
<style>
table, th, td {
	border-collapse: collapse;
	color: black;
	text-align: center;
	border-bottom: 1px solid teal;
	border-top: none;
	border-left: none;
	border-right: none;
	background-color:  rgba(224, 224, 224, 0.4) ;
}
form{
	color: teal;
	font-weight: bold;
	justify-content: space-around;
	border: teal;

}

</style>
<body id="head">
	<div class="container">
		<h2 style='color: teal; font-weight: bold; font-size: xx-large'>Voos</h2> <table class="container" style="border: #00b0e8; height: 30px; width: 100%;">
			<?php 
			echo "<tr>";
			echo "<th style='color: teal; font-weight: bold; font-size: large;'>Número Voo</th>";
			echo "<th style='color:teal; font-weight: bold; font-size: large;'>Distancia</th>";
			echo "<th style='color:teal; font-weight: bold; font-size: large;'>Companhia Aérea</th>";
			echo "<th style='color:teal; font-weight: bold; font-size: large;'>Nome Aeroporto Partida</th>";
			echo "<th style='color:teal; font-weight: bold; font-size: large;'>Nome Aeroporto Destino</th>";
			echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: large;'>Eliminar <br> Entrada</th>";
			echo "</tr>";
			foreach ($flights as $flight) {
				
				echo "<tr>";
				echo '<td>'.$flight->nvoo.'</td>';
				echo '<td>'.$flight->distancia.'</td>';
				echo '<td>'.$flight->comaerea.'</td>';
				echo '<td>'.$flight->departure->airport->nome.'</td>';
				echo '<td>'.$flight->arrival->airport->nome.'</td>';
				echo '<td><a class="btn" href="'.Url::ToRoute("flight/destroy", $flight->id).'">X</a></td>';
				echo "</tr>";
			}
			?>
		</table>
		<br>
		<br>
		<br>
		<br>
		<div class="container" style="background-color:  rgba(224, 224, 224, 0.4) ; width: 100%; padding: 20px; border-bottom: 5px;">
			<form method="POST" action="<?php Url::toRoute('flight/store')?>">
				Número Voo: <input type="text" name="nVoo" required>
				Distancia: <input type="number" name="distancia" required>
				Companhia Aérea: <input type="text" name="comAerea" required>
				Avião: <select name="airplane_id">
					<?php
					foreach($airplanes as $airplane){
						echo '<option value='.$airplane->id.'>'.$airplane->marca.'-'.$airplane->modelo.'</option>';
					}
					?>
				</select>
				<br>
				<h2 style='color: teal; font-weight: bold; font-size: large'>Partida</h2>
				Terminal: <input type="text" name="terminal" required>
				Horario de Partida: <input type="datetime-local" name="horarioPartida" required>
				Pista: <input type="text" name="pista" required><br>
				Aeroporto: <select name= "airport_id">
					<?php
					foreach($airports as $airport){
						echo '<option value='.$airport->id.'>'.$airport->nome.'</option>';
					}
					?>
				</select>
				<br>
				<h2 style='color: teal; font-weight: bold; font-size: large'>Chegada</h2>
				Terminal: <input type="text" name="terminalC" required>
				Horario de Chegada: <input type="datetime-local" name="horarioChegada" required>
				Pista: <input type="text" name="pistaC" required><br>
				Aeroporto: <select name= "airport_idC">
					<?php
					foreach($airports as $airport){
						echo '<option value='.$airport->id.'>'.$airport->nome.'</option>';
					}
					?>
				</select>
				<br>
				<br>
				<input text="Adicionar" type="submit">
			</form>
		</div>	
	</div>
</body>


<?php Layout::includeLayout('footer') ?>