<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\URL;
use Carbon\Carbon;

Layout::includeLayout('indexheader'); 
$people = Data::get('people');
$allallflights = Data::get('allflights');
$var = 1;
$varr = 0;
?>
<style>
table, th, td {
	border-collapse: collapse;
	color: black;
	text-align: center;
	border-bottom: 1px solid teal;
	border-top: none;
	border-left: none;
	border-right: none;
	background-color:  rgba(224, 224, 224, 0.4) ;
}

form{
	color: teal;
	font-weight: bold;
	justify-content: space-around;
	border: teal;

}
</style>
<body id="head">
	<div class="container" style="background-color:  rgba(224, 224, 224, 0.4) ; width: 75%; padding: 20px; border-bottom: 5px;">
		<form method="post" action="<?php Url::toRoute('pessoa/update')?>">
			Nome: <input type="text" name="nome" value="<?php echo$people->nome; ?>" required>
			<label for="m">Masculino</label>
			<?php if($people->sexo == "M"){
				echo '<input type="radio" id="m" name="sexo" value="M" checked required>
				<label for="f">Feminino</label>
				<input type="radio" id="f" name="sexo" value="F" required>';
			}else{
				echo '<input type="radio" id="m" name="sexo" value="M" required>
				<label for="f">Feminino</label>
				<input type="radio" id="f" name="sexo" value="F" checked required>';
			}
			?>
			Data de Nascimento: <input type="date" name="dtaNascimento" value="<?php echo $people->dtanascimento; ?>" required><br><br>
			NIF: <input type="text" name="nif" value="<?php echo $people->nif; ?>" required> 
			Morada: <input type="text" name="morada" value="<?php echo $people->morada; ?>" required>
			Contacto: <input type="text" name="contacto" value="<?php echo $people->contacto; ?>"required>
			<br><br>Username: <input type="text" name="username" value="<?php echo $people->username; ?>" 
			readonly>
			<input type="hidden" name="tipo" value="P">
			<br><br><input type="submit">
		</form>
	</div>
	<br>
	<div class="container">
		<?php

		echo "<p style='color: teal; font-weight: bold; font-size: xx-large;'>Historico de Bilhetes</p>";
		foreach ($allallflights as $allflights) {
			if($allflights != null){
				if($allflights[0]->ticket->idaevolta == "V"){
					$varr = 1;
				}
				for($i = 0; $i < sizeof($allflights); $i++){
					$horaembarque = new Carbon($allflights[$i]->horarioembarque);
					$horapartida = new Carbon($allflights[$i]->flight->departure->horariopartida);
					$horachegada = new Carbon($allflights[$i]->flight->arrival->horariochegada);
					if($var == 1){
						$var = 0;
						echo "<table class='container' style='width = 75%;'>";	
						echo "<h2 style='color: teal; font-weight: bold; font-size: xx-large'></h2>";
						echo "<tr>";
						echo "<th style='color: teal; font-weight: bold; font-size: medium;'>Número voo</th>";
						echo "<th style='color:teal; font-weight: bold; font-size: medium;'>Cidade</th>";
						echo "<th style='color: teal; font-weight: bold; font-size: medium;'>Data de Partida</th>";
						echo "<th style='color:teal; font-weight: bold; font-size: medium;'>Cidade</th>";
						echo "<th style='color:teal; font-weight: bold; font-size: medium;'>Data de Chegada</th>";
						echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Lugar</th>";
						echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Data de Embarque</th>";
						echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Porta de Embarque</th>";
						echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Preço</th>";
						echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Ida e Volta?</th>";

						echo '<tr>';
					}
					echo '<tr>';
					echo '<td>'.$allflights[$i]->flight->nvoo.'</td>';
					echo '<td>'.$allflights[$i]->flight->departure->airport->cidade.'</td>';
					echo '<td>'.$horapartida->toCookieString().'</td>';
					echo '<td>'.$allflights[$i]->flight->arrival->airport->cidade.'</td>';
					echo '<td>'.$horachegada->toCookieString().'</td>';
					echo '<td>'.$allflights[$i]->lugar.'</td>';
					echo '<td>'.$horaembarque->toCookieString().'</td>';
					echo '<td>'.$allflights[$i]->portaembarque.'</td>';
					if($i == 0){
						echo '<td rowspan="'.(sizeof($allflights)+5).'">'.$allflights[$i]->ticket->valor.' €</td>';
						if($varr == 1){
							echo '<td rowspan="'.(sizeof($allflights)+5).'">Sim</td>';
							$varr = 0;
						}else{
							echo '<td rowspan="'.(sizeof($allflights)+5).'">Não</td>';
						}

					}
					if($i+1 == sizeof($allflights)){
						echo '<tr>';
						echo "</table>";
						echo "<br>";
						$var = 1;
					}else{
						echo '<tr>';
					}
				}
			}
		}
		?>
	</div>

</body>

<?php Layout::includeLayout('footer') ?>