<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Url;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Redirect;

Layout::includeLayout('indexheader'); 
$peoples = Data::get('peoples');

?>
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
  color: black;
}
</style>
<header id="head">
	<div class="container ">
		<h3>Pessoal</h3> <table class="container">
		<?php 

			foreach ($peoples as $people) {
				echo "<tr>";
				echo '<td>'.$people->nome .'</td>';
				echo '<td>'.$people->username.'</td>';
				echo '<td>'.$people->tipo.'</td>';
				echo '<td><a class="btn" href="'.Url::ToRoute("pessoa/destroy", $people->id).'">X</a></td>';
				echo "</tr>";
			}
		?>
		</table>
		<br>
		<form method="post" action="<?php Url::toRoute('pessoa/store')?>">
		Nome: <input type="text" name="nome" required>
		<label for="m">Masculino</label>
		<input type="radio" id="m" name="sexo" value="M" required>
		<label for="f">Feminino</label>
		<input type="radio" id="f" name="sexo" value="F" required>
		Data de Nascimento: <input type="date" name="dtaNascimento" required>
		NIF: <input type="text" name="nif" required>
		Morada: <input type="text" name="morada" required>
		Contacto: <input type="text" name="contacto" required>
		Username: <input type="text" name="username" required>
		Palavra-Passe: <input type="password" name="palavrapasse" required>
		<select name = "tipo">
			<option value="O">Operador de Checkin</option>
			<option value="G">Gestor de Voos</option>
		</select>
		<input type="submit">
	</form>
	</div>
</header>
<?php Layout::includeLayout('footer') ?>