<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Url;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Redirect;

Layout::includeLayout('indexheader'); 
$flights = Data::get('flights');
$airports = Data::get('airports');
$airplanes = Data::get('airplanes');

?>
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
  color: black;
}
</style>
<header id="head">
	<div class="container ">
		<h3>Voos</h3> <table class="container">
		<?php 
			foreach ($flights as $flight) {
				echo "<tr>";
				echo '<td>'.$flight->nvoo.'</td>';
				echo '<td>'.$flight->distancia.'</td>';
				echo '<td>'.$flight->comaerea.'</td>';
				echo '<td>'.$flight->departure_id.'</td>';
				echo '<td>'.$flight->arrive_id.'</td>';
				echo '<td><a class="btn" href="'.Url::ToRoute("airport/destroy", $flight->id).'">X</a></td>';
				echo "</tr>";
			}
		?>
		</table>
		<br>
		<form method="POST" action="<?php Url::toRoute('flight/store')?>">
			Número Voo: <input type="text" name="nVoo" required>
			Distancia: <input type="number" name="distancia" required>
			Companhia Aérea: <input type="text" name="comAerea" required>
			Avião: <select name="airplane_id">
				<?php
					foreach($airplanes as $airplane){
						echo '<option value='.$airplane->id.'>'.$airplane->marca.'-'.$airplane->modelo.'</option>';
					}
				?>
			</select>
			<br>
			<p>Partida</p>
			Terminal: <input type="text" name="terminal" required>
			Horario de Partida: <input type="time" name="horarioPartida" required>
			Pista: <input type="text" name="pista" required>
			Aeroporto: <select name= "airport_id">
				<?php
					foreach($airports as $airport){
						echo '<option value='.$airport->id.'>'.$airport->nome.'</option>';
					}
				?>
			</select>
			<br>
			<p>Chegada</p>
			Terminal: <input type="text" name="terminalC" required>
			Horario de Chegada: <input type="time" name="horarioChegada" required>
			Pista: <input type="text" name="pistaC" required>
			Aeroporto: <select name= "airport_idC">
				<?php
					foreach($airports as $airport){
						echo '<option value='.$airport->id.'>'.$airport->nome.'</option>';
					}
				?>
			</select>
			<br>
			<br>
			<input text="Adicionar" type="submit">
		</form>
	</div>
</header>


<?php Layout::includeLayout('footer') ?>