<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Url;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Redirect;

Layout::includeLayout('indexheader'); 
$checkin = Data::get('flights');


?>
<style>
table, th, td {
    border-collapse: collapse;
    color: black;
    text-align: center;
    border-bottom: 1px solid teal;
    border-top: none;
    border-left: none;
    border-right: none;
}
</style>
<header id="head">
	<div class="container ">
		<h2 style="font-weight: bold; font-size: xx-large">Checkin</h2> <table class="container">
            <br>
            <br>
		<?php

        echo "<tr>";
        echo "<th style='color: teal; font-weight: bold; font-size: large;'>Número de Voo</th>";
        echo "<th style='color:teal; font-weight: bold; font-size: large;'>ID de Partida</th>";
        echo "<th style='color:teal; font-weight: bold; font-size: large;'>ID de Chegada</th>";
        echo "<th style='color:teal; font-weight: bold; font-size: large;'>ID do Avião</th>";
        echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: large;'>Ver <br> Passageiros</th>";
        echo "</tr>";


			foreach ($checkin as $_checkin) {
				echo "<tr>";
				echo '<td>'.$_checkin-> nvoo.'</td>';
				echo '<td>'.$_checkin-> departure_id.' </td>';
				echo '<td>'.$_checkin-> arrive_id.' </td>';
                echo '<td>'.$_checkin-> airplane_id.' </td>';
				echo '<td><a class="btn" href="'.Url::ToRoute("ticket/pessoa", $_checkin->id).'">Ver passageiros</a></td>';
				echo "</tr>";
			}
		?>
		</table>
		<br>

	</div>
</header>
<?php Layout::includeLayout('footer') ?>