<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Url;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Redirect;

Layout::includeLayout('indexheader'); 
$airports = Data::get('airports');

?>
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
  color: black;
}
</style>
<header id="head">
	<div class="container ">
		<h3>Aeroportos</h3> <table class="container">
		<?php 

			foreach ($airports as $airport) {
				echo "<tr>";
				echo '<td>'.$airport->pais .'</td>';
				echo '<td>'.$airport->cidade.'</td>';
				echo '<td>'.$airport->nome.'</td>';
				echo '<td><a class="btn" href="'.Url::ToRoute("airport/destroy", $airport->id).'">X</a></td>';
				echo "</tr>";
			}
		?>
		</table>
		<br>
		<form method="POST" action="<?php Url::toRoute('airport/store')?>">
			Pais: <input type="text" name="pais" required>
			Cidade: <input type="text" name="cidade" required>
			Nome: <input type="text" name="nome" required>
			<br>
			<br>
			<input text="Adicionar" type="submit">
		</form>
	</div>
</header>
<?php Layout::includeLayout('footer') ?>