<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Url;
use ArmoredCore\WebObjects\Data;
use Carbon\Carbon;

$entidade = Data::get('entidade');
$referencia = Data::get('referencia');
$valor = Data::get('valor');

Layout::includeLayout('indexheader'); ?>
<header id="head">
	<div class="container">
		<h3>Pagamento</h3>
		<p>Entidade - <?php echo $entidade?></p>	
		<p>Referencia - <?php echo $referencia?></p>	
		<p>Valor - <?php echo $valor?></p>
		<br>
		<a class="btn" href="<?php echo Url::ToRoute("home/index")?>">Voltar</a>
	</div>
</header>
<?php Layout::includeLayout('footer') ?>