<?php 
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('indexheader'); 

?>

<header id="head">
<div class="container">
	<form method="post" action="<?php Url::toRoute('pessoa/store')?>">
		Nome: <input type="text" name="nome" required>
		<label for="m">Masculino</label>
		<input type="radio" id="m" name="sexo" value="M" required>
		<label for="f">Feminino</label>
		<input type="radio" id="f" name="sexo" value="F" required>
		Data de Nascimento: <input type="date" name="dtaNascimento" required>
		NIF: <input type="text" name="nif" required>
		Morada: <input type="text" name="morada" required>
		Contacto: <input type="text" name="contacto" required>
		Username: <input type="text" name="username" required>
		Palavra-Passe: <input type="password" name="palavrapasse" required>
		<input type="hidden" name="tipo" value="P">
		<input type="submit">
	</form>
</div>
</header>
<?php Layout::includeLayout('footer') ?>