<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Url;
use ArmoredCore\WebObjects\Data;
use Carbon\Carbon;

$_SESSION['Volta'] = false;
$GLOBALS['precokm'] = 0.11;
$searched_flight = Data::get('searched_flight');
$searched_flight_onestop = Data::get('searched_flight_onestop');
$searched_flight_twostop = Data::get('searched_flight_twostop');
$idaevolta = Data::get('idaevolta');
Layout::includeLayout('indexheader'); ?>

<style>
table, th, td {
	border-collapse: collapse;
	color: black;
	text-align: center;
	border-bottom: 1px solid teal;
	border-top: none;
	border-left: none;
	border-right: none;
	background-color:  rgba(224, 224, 224, 0.4) ;
}
form{
	color: teal;
	font-weight: bold;
	justify-content: space-around;
	border: teal;

}
</style>
<body id="head">
	<div class="container" style="background-color:  rgba(224, 224, 224, 0.4) ; width: 50%; padding: 20px; border-bottom: 5px;">
		<form method="POST" action="<?php Url::toRoute('flight/find')?>">
			Partida: <input type="search" name="partida" required>
			Chegada: <input type="search" name="chegada" required>
			Data: <input type="date" name="data" value="null"><br><br>
			<label for="ida">Só Ida</label>
			<input type="radio" id="ida" name="idaevolta" value="I" checked required>
			<label for="volta">Ida e Volta</label>
			<input type="radio" id="volta" name="idaevolta" value="V" required>
			Data de Regresso: <input type="date" name="datavolta" value="null">
			<br>
			<br>
			<input type="submit" value="Procurar">
		</form>
	</div>
	<?php 
	if ($_SERVER['REQUEST_METHOD'] === 'POST')
	{
		if(sizeof($searched_flight) != 0){
			echo "<h2 style='color: teal; font-weight: bold; font-size: xx-large'>Voo Directo</h2>";
			echo "<table class='container' style='width: 75%'>";
			echo "<tr>";
			echo "<th style='color: teal; font-weight: bold; font-size: medium;'>Cidade</th>";
			echo "<th style='color:teal; font-weight: bold; font-size: medium;'>Nome do Aeroporto</th>";
			echo "<th style='color: teal; font-weight: bold; font-size: medium;'>Cidade</th>";
			echo "<th style='color:teal; font-weight: bold; font-size: medium;'>Nome do Aeroporto</th>";
			echo "<th style='color:teal; font-weight: bold; font-size: medium;'>Número Voo</th>";
			echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Distancia</th>";
			echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Companhia Aérea</th>";
			echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Data Partida</th>";
			echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Data Chegada</th>";
			if($idaevolta != 'V')
				echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Preço</th>";
			echo "</tr>";
		}
		foreach ($searched_flight as $flight) {
			$datepartida = new Carbon($flight->departure->horariopartida);
			$datechegada = new Carbon($flight->arrival->horariochegada);
			echo "<tr>";
			echo '<td>'.$flight->departure->airport->cidade.'</td>';
			echo '<td>'.$flight->departure->airport->nome.'</td>';
			echo '<td>'.$flight->arrival->airport->cidade.'</td>';
			echo '<td>'.$flight->arrival->airport->nome.'</td>';
			echo '<td>'.$flight->nvoo.'</td>';
			echo '<td>'.$flight->distancia.'</td>';
			echo '<td>'.$flight->comaerea.'</td>';
			echo '<td>'.$datepartida->toCookieString().'</td>';
			echo '<td>'.$datechegada->toCookieString().'</td>';
			global $precokm;
			$preco = $flight->distancia*$precokm;

			if($idaevolta != 'V'){
				echo '<td>'.$preco.'€</td>';
				if($_SESSION['Tipo'] == 'P'){
					echo '<td><a class="btn" href="'.Url::ToRoute("ticket/comprar", $flight->id).'">Comprar</a></td>';
				}
			}else{
				if($_SESSION['Tipo'] == 'P'){
					echo '<td><a class="btn" href="'.Url::ToRoute("flight/volta", $flight->id).'">Selecionar voo de volta</a></td>';
				}
			}
			echo "</tr>";
		}
	}
	
	?>
</table>
<?php
if ($_SERVER['REQUEST_METHOD'] === 'POST')
{
	if(sizeof($searched_flight_onestop) > 0 ) {
		echo "<h2 style='color: teal; font-weight: bold; font-size: xx-large'>Voos Com Ligação</h2>";
		echo "<table class='container'  style='width: 75%'>";
		echo "<tr>";
		echo "<th style='color: teal; font-weight: bold; font-size: medium;'>Cidade</th>";
		echo "<th style='color:teal; font-weight: bold; font-size: medium;'>Nome do Aeroporto</th>";
		echo "<th style='color: teal; font-weight: bold; font-size: medium;'>Cidade</th>";
		echo "<th style='color:teal; font-weight: bold; font-size: medium;'>Nome do Aeroporto</th>";
		echo "<th style='color:teal; font-weight: bold; font-size: medium;'>Número Voo</th>";
		echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Distancia</th>";
		echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Companhia Aérea</th>";
		echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Data Partida</th>";
		echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Data Chegada</th>";
		if($idaevolta != 'V')
			echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Preço</th>";
		echo "</tr>";

		for($i = 0; $i < sizeof($searched_flight_onestop); $i++){
			$datepartida = new Carbon($searched_flight_onestop[$i]->departure->horariopartida);
			$datechegada = new Carbon($searched_flight_onestop[$i]->arrival->horariochegada);
			echo "<tr>";
			echo '<td>'.$searched_flight_onestop[$i]->departure->airport->cidade.'</td>';
			echo '<td>'.$searched_flight_onestop[$i]->departure->airport->nome.'</td>';
			echo '<td>'.$searched_flight_onestop[$i]->arrival->airport->cidade.'</td>';
			echo '<td>'.$searched_flight_onestop[$i]->arrival->airport->nome.'</td>';
			echo '<td>'.$searched_flight_onestop[$i]->nvoo.'</td>';
			echo '<td>'.$searched_flight_onestop[$i]->distancia.'</td>';
			echo '<td>'.$searched_flight_onestop[$i]->comaerea.'</td>';
			echo '<td>'.$datepartida->toCookieString().'</td>';
			echo '<td>'.$datechegada->toCookieString().'</td>';
			if($i % 2 == 0){
				global $precokm;
				$preco = (($searched_flight_onestop[$i]->distancia + $searched_flight_onestop[$i+1]->distancia) * $precokm);

				$stringflight = $searched_flight_onestop[$i]->id . "," . $searched_flight_onestop[$i+1]->id;

				if($idaevolta != 'V'){
					echo '<td rowspan="2">'.$preco.'€</td>';
					$stringflight = $searched_flight_onestop[$i]->id . "," . $searched_flight_onestop[$i+1]->id;
					if($_SESSION['Tipo'] == 'P'){
						echo '<td rowspan="2"><a class="btn" href="'.Url::ToRoute("ticket/comprar", $stringflight).'">Comprar</a></td>';
					}
				}else{
					if($_SESSION['Tipo'] == 'P'){
						echo '<td rowspan="2"><a class="btn" href="'.Url::ToRoute("flight/volta", $stringflight).'">Selecionar voo de volta</a></td>';
					}

				}
			}
			echo "</tr>";
		}
	}
}
?>
</table>
<?php
if ($_SERVER['REQUEST_METHOD'] === 'POST')
{
	if(sizeof($searched_flight_twostop) > 0 ) {
		echo "<h2 style='color: teal; font-weight: bold; font-size: xx-large'>Voos Com Duas Ligações</h2>";
		echo "<table class='container'  style='width: 75%'>";
		echo "<tr>";
		echo "<th style='color: teal; font-weight: bold; font-size: medium;'>Cidade</th>";
		echo "<th style='color:teal; font-weight: bold; font-size: medium;'>Nome do Aeroporto</th>";
		echo "<th style='color: teal; font-weight: bold; font-size: medium;'>Cidade</th>";
		echo "<th style='color:teal; font-weight: bold; font-size: medium;'>Nome do Aeroporto</th>";
		echo "<th style='color:teal; font-weight: bold; font-size: medium;'>Número Voo</th>";
		echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Distancia</th>";
		echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Companhia Aérea</th>";
		echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Data Partida</th>";
		echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Data Chegada</th>";
		if($idaevolta != 'V')
			echo "<th style='color: teal; width: px50px; font-weight: bold; font-size: medium;'>Preço</th>";
		echo "</tr>";
		for($i = 0; $i < sizeof($searched_flight_twostop); $i++){
			$datepartida = new Carbon($searched_flight_twostop[$i]->departure->horariopartida);
			$datechegada = new Carbon($searched_flight_twostop[$i]->arrival->horariochegada);
			echo "<tr>";
			echo '<td>'.$searched_flight_twostop[$i]->departure->airport->cidade.'</td>';
			echo '<td>'.$searched_flight_twostop[$i]->departure->airport->nome.'</td>';
			echo '<td>'.$searched_flight_twostop[$i]->arrival->airport->cidade.'</td>';
			echo '<td>'.$searched_flight_twostop[$i]->arrival->airport->nome.'</td>';
			echo '<td>'.$searched_flight_twostop[$i]->nvoo.'</td>';
			echo '<td>'.$searched_flight_twostop[$i]->distancia.'</td>';
			echo '<td>'.$searched_flight_twostop[$i]->comaerea.'</td>';
			echo '<td>'.$datepartida->toCookieString().'</td>';
			echo '<td>'.$datechegada->toCookieString().'</td>';
			if($i % 3 == 0){
				global $precokm;

				$preco = ($searched_flight_twostop[$i]->distancia + $searched_flight_twostop[$i+1]->distancia + $searched_flight_twostop[$i+2]->distancia) * $precokm;

				$stringflight = $searched_flight_twostop[$i]->id. "," .$searched_flight_twostop[$i+1]->id. "," .$searched_flight_twostop[$i+2]->id;
				if($idaevolta != 'V'){
					echo '<td rowspan="3">'.$preco.'€</td>';
					if($_SESSION['Tipo'] == 'P'){
						echo '<td rowspan="3"><a class="btn" href="'.Url::ToRoute("ticket/comprar", $stringflight).'">Comprar</a></td>';
					}
				}else{
					if($_SESSION['Tipo'] == 'P'){
						echo '<td rowspan="3"><a class="btn" href="'.Url::ToRoute("flight/volta", $stringflight).'">Selecionar voo de volta</a></td>';
					}
				}
				echo "</tr>";
			}
		}
	}
	
	if((sizeof($searched_flight_twostop) == 0 ) && (sizeof($searched_flight_onestop) == 0 ) && (sizeof($searched_flight) == 0)){
		echo "<h2 style='color: teal; font-weight: bold; font-size: xx-large'>Não existem voos disponiveis</h2>";
	}

}
?>
</table>
</div>
<br>
<br>
<br>
<br>
</body>

<?php Layout::includeLayout('footer') ?>
