<?php
use ArmoredCore\Controllers\BaseController;
use ArmoredCore\Interfaces\ResourceControllerInterface;
use ArmoredCore\WebObjects\Post;
use ArmoredCore\WebObjects\Redirect;
use ArmoredCore\WebObjects\View;

/**
 * CRUD Resource Controller for ActiveRecord Model aviao
 *
 * Code generated by WebLogicMVC Code Builder
 *
 * Date: 2021-05-24
 *
 * WL Code Builder developed by Sílvio Priem Mendes
 * *
 */
class aviaoController extends BaseController implements ResourceControllerInterface
{
	/**
	 * Returns index view with all records
	 */
	public function index()
	{
		$aviaos = aviao::all();
		return View::make('aviao.index', ['aviaos' => $aviaos]);
	}


	/**
	 * Returns a view with a form to create a new record
	 */
	public function create()
	{
		return View::make('aviao.create');
	}


	/**
	 * Receives new record data through POST method and stores it in the DB table
	 */
	public function store()
	{
		//create new resource (activerecord/model) instance with data from POST
		//your form name fields must match the ones of the table fields
		$aviao = new aviao(Post::getAll());

		if($aviao->is_valid()){
		    $aviao->save();
		    Redirect::toRoute('aviao/index');
		} else {
		    //redirect to form with data and errors
		    Redirect::flashToRoute('aviao/create', ['aviao' => $aviao]);
		}
	}


	/**
	 * return a detailed view with record where PK = $id
	 */
	public function show($id)
	{
		$aviao = aviao::find([$id]);

		if (is_null($aviao)) {
		   //TODO redirect to standard error page
		} else {
		    return View::make('aviao.show', ['aviao' => $aviao]);
		}
	}


	/**
	 * return a editable form view with record where PK = $id
	 */
	public function edit($id)
	{
		$aviao = aviao::find([$id]);

		if (is_null($aviao)) {
		   //TODO redirect to standard error page
		} else {
		    return View::make('aviao.edit', ['aviao' => $aviao]);
		}
	}


	/**
	 * Receives record data through POST method and updates it in the DB table
	 */
	public function update($id)
	{
		//find resource (activerecord/model) instance where PK = $id
		//your form name fields must match the ones of the table fields
		$aviao = aviao::find([$id]);
		$aviao->update_attributes(Post::getAll());

		if($aviao->is_valid()){
		    $aviao->save();
		    Redirect::toRoute('aviao/index');
		} else {
		    //redirect to form with data and errors
		    Redirect::flashToRoute('aviao/edit', ['aviao' => $aviao]);
		}
	}


	/**
	 * deletes the record where PK = $id
	 */
	public function destroy($id)
	{
		$aviao = aviao::find([$id]);
		$aviao->delete();
		Redirect::toRoute('aviao/index');
	}
}