<?php
use ArmoredCore\Controllers\BaseController;
use ArmoredCore\Interfaces\ResourceControllerInterface;
use ArmoredCore\WebObjects\Post;
use ArmoredCore\WebObjects\Redirect;
use ArmoredCore\WebObjects\View;

/**
 * CRUD Resource Controller for ActiveRecord Model bilhete
 *
 * Code generated by WebLogicMVC Code Builder
 *
 * Date: 2021-05-24
 *
 * WL Code Builder developed by Sílvio Priem Mendes
 * *
 */
class bilheteController extends BaseController implements ResourceControllerInterface
{
	/**
	 * Returns index view with all records
	 */
	public function index()
	{
		$bilhetes = bilhete::all();
		return View::make('bilhete.index', ['bilhetes' => $bilhetes]);
	}


	/**
	 * Returns a view with a form to create a new record
	 */
	public function create()
	{
		return View::make('bilhete.create');
	}


	/**
	 * Receives new record data through POST method and stores it in the DB table
	 */
	public function store()
	{
		//create new resource (activerecord/model) instance with data from POST
		//your form name fields must match the ones of the table fields
		$bilhete = new bilhete(Post::getAll());

		if($bilhete->is_valid()){
		    $bilhete->save();
		    Redirect::toRoute('bilhete/index');
		} else {
		    //redirect to form with data and errors
		    Redirect::flashToRoute('bilhete/create', ['bilhete' => $bilhete]);
		}
	}


	/**
	 * return a detailed view with record where PK = $id
	 */
	public function show($id)
	{
		$bilhete = bilhete::find([$id]);

		if (is_null($bilhete)) {
		   //TODO redirect to standard error page
		} else {
		    return View::make('bilhete.show', ['bilhete' => $bilhete]);
		}
	}


	/**
	 * return a editable form view with record where PK = $id
	 */
	public function edit($id)
	{
		$bilhete = bilhete::find([$id]);

		if (is_null($bilhete)) {
		   //TODO redirect to standard error page
		} else {
		    return View::make('bilhete.edit', ['bilhete' => $bilhete]);
		}
	}


	/**
	 * Receives record data through POST method and updates it in the DB table
	 */
	public function update($id)
	{
		//find resource (activerecord/model) instance where PK = $id
		//your form name fields must match the ones of the table fields
		$bilhete = bilhete::find([$id]);
		$bilhete->update_attributes(Post::getAll());

		if($bilhete->is_valid()){
		    $bilhete->save();
		    Redirect::toRoute('bilhete/index');
		} else {
		    //redirect to form with data and errors
		    Redirect::flashToRoute('bilhete/edit', ['bilhete' => $bilhete]);
		}
	}


	/**
	 * deletes the record where PK = $id
	 */
	public function destroy($id)
	{
		$bilhete = bilhete::find([$id]);
		$bilhete->delete();
		Redirect::toRoute('bilhete/index');
	}
}