<?php
use ArmoredCore\Controllers\BaseController;
use ArmoredCore\Interfaces\ResourceControllerInterface;
use ArmoredCore\WebObjects\Post;
use ArmoredCore\WebObjects\Redirect;
use ArmoredCore\WebObjects\View;

/**
 * CRUD Resource Controller for ActiveRecord Model ticket__flight
 *
 * Code generated by WebLogicMVC Code Builder
 *
 * Date: 2021-06-11
 *
 * WL Code Builder developed by Sílvio Priem Mendes
 * *
 */
class ticket__flightController extends BaseController implements ResourceControllerInterface
{
	/**
	 * Returns index view with all records
	 */
	public function index()
	{
		$ticket__flights = ticket__flight::all();
		return View::make('ticket__flight.index', ['ticket__flights' => $ticket__flights]);
	}


	/**
	 * Returns a view with a form to create a new record
	 */
	public function create()
	{
		return View::make('ticket__flight.create');
	}


	/**
	 * Receives new record data through POST method and stores it in the DB table
	 */
	public function store()
	{
		//create new resource (activerecord/model) instance with data from POST
		//your form name fields must match the ones of the table fields
		$ticket__flight = new ticket__flight(Post::getAll());

		if($ticket__flight->is_valid()){
		    $ticket__flight->save();
		    Redirect::toRoute('ticket__flight/index');
		} else {
		    //redirect to form with data and errors
		    Redirect::flashToRoute('ticket__flight/create', ['ticket__flight' => $ticket__flight]);
		}
	}


	/**
	 * return a detailed view with record where PK = $id
	 */
	public function show($id)
	{
		$ticket__flight = ticket__flight::find([$id]);

		if (is_null($ticket__flight)) {
		   //TODO redirect to standard error page
		} else {
		    return View::make('ticket__flight.show', ['ticket__flight' => $ticket__flight]);
		}
	}


	/**
	 * return a editable form view with record where PK = $id
	 */
	public function edit($id)
	{
		$ticket__flight = ticket__flight::find([$id]);

		if (is_null($ticket__flight)) {
		   //TODO redirect to standard error page
		} else {
		    return View::make('ticket__flight.edit', ['ticket__flight' => $ticket__flight]);
		}
	}


	/**
	 * Receives record data through POST method and updates it in the DB table
	 */
	public function update($id)
	{
		//find resource (activerecord/model) instance where PK = $id
		//your form name fields must match the ones of the table fields
		$ticket__flight = ticket__flight::find([$id]);
		$ticket__flight->update_attributes(Post::getAll());

		if($ticket__flight->is_valid()){
		    $ticket__flight->save();
		    Redirect::toRoute('ticket__flight/index');
		} else {
		    //redirect to form with data and errors
		    Redirect::flashToRoute('ticket__flight/edit', ['ticket__flight' => $ticket__flight]);
		}
	}


	/**
	 * deletes the record where PK = $id
	 */
	public function destroy($id)
	{
		$ticket__flight = ticket__flight::find([$id]);
		$ticket__flight->delete();
		Redirect::toRoute('ticket__flight/index');
	}
}

?>