
<footer id="footer" class="top-space">

    <div class="footer1">
        <div class="container">
            <div class="row">

                <div class="col-md-3 widget">
                    <h3 class="widget-title">Contactos</h3>
                    <div class="widget-body">
                        <p>+351 256 100 220<br>
                            <a href="mailto:#">flight@travel.air</a><br>
                            <br>
                            Flight Travel Airs Agency<br>
                            Aeoroporto de Lisboa<br>
                            Alameda das Comunidades<br>
                            1700-111, Lisboa<br>
                            Portugal<br>
                        </p>
                    </div>
                </div>
                <div class="col-md-6 widget">
                    <div class="widget-body">
                        <p>Voar não consiste em levantar voo, mas também em aterrar em segurança.</p>
                    </div>
                    <h3 class="widget-title">Vasco Ferreira, 2010</h3>
                </div>

            </div> <!-- /row of widgets -->
        </div>
    </div>

<div class="footer2">
    <div class="container">
        <div class="row">



            <div class="col-md-6 widget">
                <div class="widget-body">
                    <p class="text-right" style="text-align: left;" >
                        Copyright &copy; 2016-2021, Silvio Priem Mendes, PhD. <br> Site template by Sergey Pozhilov.
                    </p>
                </div>
            </div>

        </div> <!-- /row of widgets -->
    </div>
</div>

</footer>

<!-- JavaScript libs are placed at the end of the document so the pages load faster -->

<?php
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\Facades\DebugRenderer;
?>

<?= AssetBundler::js()?>

<script>hljs.initHighlightingOnLoad();</script>

</body>
</html>