<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('indexheader'); ?>
    <!-- Header -->
    <header id="head">
        <div class="container" style="background-color: #00b0e8; width: 500px; padding: 20px; border-bottom: 5px">
            <div class="row">
                <h1 class="lead"><b>FlightTravelAir</b><br> <br> Encontre o Voo que Deseja<br></h1>

                <p><a class="btn btn-action btn-lg" role="button" href="<?= Url::toRoute('home/start')?>">PROCURAR</a></p>
                <p class="small"><i> </i></p>
            </div>
        </div>
    </header>
    <!-- /Header -->


</div>	<!-- /container -->

<?php Layout::includeLayout('footer')?>