<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('indexheader'); ?>

<style>
form{
    color: teal;
    font-weight: bold;
    justify-content: space-around;
    border: teal;

}
</style>    
<body id="head">
    <div class="container" style="background-color:  rgba(224, 224, 224, 0.4) ; width: 1000px; padding: 20px; border-bottom: 5px">
        <div class="row">
            <h2 style='color: teal; font-weight: bold; font-size: large'>Procurar Voos</h2>
            <br>
            <form method="POST" action="<?php Url::toRoute('flight/find')?>">
                Partida: <input type="search" name="partida" required>
                Chegada: <input type="search" name="chegada" required>
                Data: <input type="date" name="data" value="null"><br><br>
                <label for="ida">Só Ida</label>
                <input type="radio" id="ida" name="idaevolta" value="I" checked required>
                <label for="volta">Ida e Volta</label>
                <input type="radio" id="volta" name="idaevolta" value="V" required>
                Data de Regresso: <input type="date" name="datavolta" value="null">
                <br>
                <br>
                <input type="submit" value="Procurar">
            </form>
        </div>
    </div>
</body>

<?php Layout::includeLayout('footer')?>