<?php use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Url;


Layout::includeLayout('indexheader') ?>
<body id="head">
	<!-- container -->
	<div class="row">
		
		<!-- Article main content -->
		<article class="col-xs-12 maincontent">
			<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
				<div class="panel panel-default">
					<div class="panel-body" style="background-color:  rgba(224, 224, 224, 0.4);">
						<h3 class="thin text-center" style='color: teal;'>Login</h3>
						<p class="text-center text-muted" style='color: teal;'>Se não tiver conta, faça o seu registo <a href="<?php echo Url::toRoute('pessoa/create') ?>">aqui</a></p>
						<hr>
						
						<form method="post" action="<?php Url::toRoute('pessoa/verifylogin')?>">
							<div class="top-margin">
								<label>Username/Email <span class="text-danger">*</span></label>
								<input type="text" class="form-control" name="username">
							</div>
							<div class="top-margin">
								<label>Password <span class="text-danger">*</span></label>
								<input type="password" class="form-control" name="password">
							</div>

							<hr>

							<div class="row">
								<div class="col-lg-12 text-right">
									<button class="btn btn-action" type="submit">Sign in</button>
								</div>
							</div>
						</form>
					</div>
				</div>

			</div>
			
		</article>
		<!-- /Article -->

	</div>
</div>	<!-- /container -->
</body>
<?php Layout::includeLayout('footer') ?>