<?php
use ArmoredCore\Controllers\BaseController;
use ArmoredCore\Interfaces\ResourceControllerInterface;
use ArmoredCore\WebObjects\Post;
use ArmoredCore\WebObjects\Redirect;
use ArmoredCore\WebObjects\View;

/**
 * CRUD Resource Controller for ActiveRecord Model departure
 *
 * Code generated by WebLogicMVC Code Builder
 *
 * Date: 2021-06-11
 *
 * WL Code Builder developed by Sílvio Priem Mendes
 * *
 */
class departureController extends BaseController implements ResourceControllerInterface
{
	/**
	 * Returns index view with all records
	 */
	public function index()
	{
		$departures = departure::all();
		return View::make('departure.index', ['departures' => $departures]);
	}


	/**
	 * Returns a view with a form to create a new record
	 */
	public function create()
	{
		return View::make('departure.create');
	}


	/**
	 * Receives new record data through POST method and stores it in the DB table
	 */
	public function store()
	{
		//create new resource (activerecord/model) instance with data from POST
		//your form name fields must match the ones of the table fields
		$departure = new departure(Post::getAll());

		if($departure->is_valid()){
		    $departure->save();
		    Redirect::toRoute('departure/index');
		} else {
		    //redirect to form with data and errors
		    Redirect::flashToRoute('departure/create', ['departure' => $departure]);
		}
	}


	/**
	 * return a detailed view with record where PK = $id
	 */
	public function show($id)
	{
		$departure = departure::find([$id]);

		if (is_null($departure)) {
		   //TODO redirect to standard error page
		} else {
		    return View::make('departure.show', ['departure' => $departure]);
		}
	}


	/**
	 * return a editable form view with record where PK = $id
	 */
	public function edit($id)
	{
		$departure = departure::find([$id]);

		if (is_null($departure)) {
		   //TODO redirect to standard error page
		} else {
		    return View::make('departure.edit', ['departure' => $departure]);
		}
	}


	/**
	 * Receives record data through POST method and updates it in the DB table
	 */
	public function update($id)
	{
		//find resource (activerecord/model) instance where PK = $id
		//your form name fields must match the ones of the table fields
		$departure = departure::find([$id]);
		$departure->update_attributes(Post::getAll());

		if($departure->is_valid()){
		    $departure->save();
		    Redirect::toRoute('departure/index');
		} else {
		    //redirect to form with data and errors
		    Redirect::flashToRoute('departure/edit', ['departure' => $departure]);
		}
	}


	/**
	 * deletes the record where PK = $id
	 */
	public function destroy($id)
	{
		$departure = departure::find([$id]);
		$departure->delete();
		Redirect::toRoute('departure/index');
	}
}


?>